#!/bin/bash

set -euo pipefail

readonly dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

pushd "${dir}"
trap 'popd' EXIT

./generate-ca
./generate-admin-cert
./generate-worker-certs
./generate-kube-proxy-cert
./generate-kubernetes-cert
