#!/bin/bash

set -euo pipefail

readonly dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd "${dir}/../certificates"
trap 'popd' EXIT

pwd

../tools/cfssl gencert -initca ca-csr.json | ../tools/cfssljson -bare ca
