#!/bin/bash

set -euo pipefail

readonly dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

kubectl config set-cluster kubernetes-the-hard-way \
  --certificate-authority="${dir}/../certificates/ca.pem" \
  --embed-certs=true \
  --server=https://192.168.199.10:6443 \
  --kubeconfig="${dir}/../config/kube-controller-manager.kubeconfig"

kubectl config set-credentials system:kube-controller-manager \
  --client-certificate="${dir}/../certificates/kube-controller-manager.pem" \
  --client-key="${dir}/../certificates/kube-controller-manager-key.pem" \
  --embed-certs=true \
  --kubeconfig="${dir}/../config/kube-controller-manager.kubeconfig"

kubectl config set-context default \
  --cluster=kubernetes-the-hard-way \
  --user=system:kube-controller-manager \
  --kubeconfig="${dir}/../config/kube-controller-manager.kubeconfig"

kubectl config use-context default --kubeconfig="${dir}/../config/kube-controller-manager.kubeconfig"
