#!/bin/bash

set -euo pipefail

readonly bindir="${BINDIR:-/usr/local/bin}"
readonly dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly tmpdir=$(mktemp -d /tmp/kubernetes-the-hard-way-XXXXXX)
mkdir -p "${tmpdir}"

pushd "${tmpdir}"
trap 'popd; rm -rf "${tmpdir}"' EXIT

# shellcheck source=versions.bash
source "${dir}/versions.bash"

curl -sSL \
  -O "https://pkg.cfssl.org/${cfssl_version}/cfssl_linux-amd64" \
  -O "https://pkg.cfssl.org/${cfssl_version}/cfssljson_linux-amd64"

chmod +x cfssl_linux-amd64 cfssljson_linux-amd64

mv -v cfssl_linux-amd64 "${BINDIR}/cfssl"
mv -v cfssljson_linux-amd64 "${BINDIR}/cfssljson"

curl -ssL \
  -O "https://storage.googleapis.com/kubernetes-release/release/${k8s_version}/bin/linux/amd64/kubectl"

chmod +x kubectl

mv -v kubectl "${BINDIR}"
