#!/bin/bash

set -euo pipefail

readonly dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd "${dir}/../"
trap 'popd' EXIT

./scripts/distclean
./scripts/download-tools
vagrant up
./scripts/generate-certs
./scripts/generate-kubeconfig-kube-proxy
./scripts/generate-kubeconfig-worker
./scripts/setup-etcd
./scripts/setup-controller-services
./scripts/setup-kubelet-api-cluster-role
./scripts/setup-worker-services
./scripts/configure-kubectl-on-host
./scripts/setup-networking
echo -e "\033[1mFinished. Cluster should be healthy and soon in state ready:\033[0m"
kubectl get componentstatuses
kubectl get nodes
