#!/bin/bash

set -euo pipefail

# As mentioned in https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#install
kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')
